# Generated by Django 3.0.7 on 2020-06-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_list_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
    ]
